Logstash for CloudWatch Alarms
Bit-Clouded/Angostura pull request #6
Opened 2019-09-26 09:37 UTC by imomou

Hi Bit-Cloudeders

This is a logstash processing to ElasticSearch specifically for SNS CloudWatch Alarms, I think you will find this useful.

Regards
Imomou

2019-09-26 09:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Bit-Clouded/Angostura?pullRequest=6) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/Bit-Clouded/Angostura?pullRequest=6) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: imomou<br/>:x: root<br/><hr/>**root** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Bit-Clouded/Angostura?pullRequest=6) it.</sub>

2019-09-27 01:58 UTC, SleeperSmith requested changes

2019-09-27 01:58 UTC, SleeperSmith commented on analytics/ls-aws-sqs-default/Dockerfile
> +FROM docker.elastic.co/logstash/logstash:6.5.1
Please change to using logstash-oss
https://github.com/Bit-Clouded/Angostura/blob/8dc75b5b7fcfbc7e0d29454140afaf9b79ef5f5c/analytics/ls-aws-kinesis/Dockerfile#L1

2019-09-27 01:58 UTC, SleeperSmith commented on analytics/ls-aws-sqs-default/ls-aws-sqs3-default.conf
> +		mutate {
This shouldn't be indented to second level. As well as the rest of this section

2019-09-27 01:58 UTC, SleeperSmith commented on analytics/ls-aws-sqs-default/Dockerfile
> +RUN bin/logstash-plugin install --no-verify
Please remove this line.

2019-10-01 00:54 UTC, SleeperSmith approved these changes

2019-10-01 00:54 UTC, imomou commented
Hi, about the CLA, the root user actually comes from me (imomou), encase you're wondering why they coming from

2019-10-01 00:55 UTC, merged